kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: storageos:operator
subjects:
- kind: ServiceAccount
  name: storageos-operator
  namespace: storageos-operator
roleRef:
  kind: ClusterRole
  name: storageos-operator
  apiGroup: rbac.authorization.k8s.io
